# Generated by Django 5.2.6 on 2025-09-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=10, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_section', models.CharField(blank=True, max_length=50, null=True)),
                ('form_photo', models.ImageField(blank=True, null=True, upload_to='form_photos/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('e_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(blank=True, default='no', max_length=20, null=True)),
            ],
        ),
    ]
